AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - lib/tasks/**/*.rake
    - db/**/*.rb
    - spec/**/*.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
