AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - lib/tasks/**/*.rake
    - db/**/*.rb
    - spec/**/*.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
